SELECT i.ID, ni.FISH_NAME, i.LENGTH
FROM FISH_INFO i
JOIN FISH_NAME_INFO ni ON i.FISH_TYPE = ni.FISH_TYPE
WHERE (i.FISH_TYPE, i.LENGTH) IN (
    SELECT FISH_TYPE, MAX(LENGTH)
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)
ORDER BY ID ASC;