SELECT d.ID, COALESCE(j.CHILD_COUNT, 0) CHILD_COUNT
FROM ECOLI_DATA d
LEFT JOIN (
    SELECT PARENT_ID, COUNT(*) CHILD_COUNT
    FROM ECOLI_DATA
    GROUP BY PARENT_ID
    HAVING PARENT_ID IS NOT NULL
) j ON d.ID = j.PARENT_ID
ORDER BY d.ID;